spring.application.name=Customer Management
spring.mvc.locale-resolver=accept-header
spring.mvc.locale=de
spring.messages.basename=ValidationMessages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
# only activate profile local, when running from locally
spring.config.import=optional:file:./spring.profiles.active.local.properties
todo.url=https://jsonplaceholder.typicode.com
